'use client'
import React from 'react'
import { cn } from "@/lib/utils";
import { ResponsiveInput, ColorPicker, RangeInput, ResponsiveRadio, ResponsiveStyles, normalizeResponsive } from '../core'

export const OneBlock = {
    fields: {
        layout: {
            type: 'select', label: 'Layout Style',
            options: [{ label: 'Full Width (100%)', value: '100' }, { label: '50/50 (Flexible Split)', value: '50-50' }, { label: 'Triple (33/33/33)', value: '33-33-33' }]
        },
        mobileLayout: { type: 'radio', label: 'Mobile Behavior', options: [{ label: 'Stack (Vertical)', value: 'stack' }, { label: 'Keep Beside (Row)', value: 'row' }] },
        flexRatio: { type: 'custom', label: 'Column Split Ratio', render: RangeInput },
        width: { type: 'custom', label: 'Width', render: ResponsiveInput }, height: { type: 'custom', label: 'Height', render: ResponsiveInput }, backgroundColor: { type: 'custom', label: 'Background Color', render: ColorPicker }, padding: { type: 'custom', label: 'Padding', render: ResponsiveInput }, borderRadius: { type: 'text', label: 'Border Radius' }, gap: { type: 'custom', label: 'Gap', render: ResponsiveInput },
        objectFit: { type: 'select', label: 'Object Fit', options: [{ label: 'Contain', value: 'contain' }, { label: 'Cover', value: 'cover' }, { label: 'Fill', value: 'fill' }] },
        leftColumnBg: { type: 'custom', label: 'Left Col Background', render: ColorPicker }, leftColumnPadding: { type: 'text', label: 'Left Col Padding' }, leftColumnRadius: { type: 'text', label: 'Left Col Radius' }, rightColumnBg: { type: 'custom', label: 'Right Col Background', render: ColorPicker }, rightColumnPadding: { type: 'text', label: 'Right Col Padding' }, rightColumnRadius: { type: 'text', label: 'Right Col Radius' },
        display: { type: 'radio', label: 'Display', options: [{ label: 'Block', value: 'block' }, { label: 'Flex', value: 'flex' }, { label: 'Grid', value: 'grid' }] },
        justifyContent: { type: 'radio', label: 'Content Alignment', options: [{ label: 'Left', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'flex-end' }] },
        alignment: { type: 'radio', label: 'Box Alignment', options: [{ label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }] },
        borderWidth: { type: 'text', label: 'Border Width' }, borderStyle: { type: 'select', label: 'Border Style', options: [{ label: 'None', value: 'none' }, { label: 'Solid', value: 'solid' }, { label: 'Dashed', value: 'dashed' }, { label: 'Dotted', value: 'dotted' }] }, borderColor: { type: 'custom', label: 'Border Color', render: ColorPicker },
        zoneBackgroundColor: { type: 'custom', label: 'Zone Background Color', render: ColorPicker }, zoneBorderWidth: { type: 'text', label: 'Zone Border Width' }, zoneBorderStyle: { type: 'select', label: 'Zone Border Style', options: [{ label: 'None', value: 'none' }, { label: 'Solid', value: 'solid' }, { label: 'Dashed', value: 'dashed' }, { label: 'Dotted', value: 'dotted' }] }, zoneBorderColor: { type: 'custom', label: 'Zone Border Color', render: ColorPicker }, zoneBorderRadius: { type: 'text', label: 'Zone Border Radius' },
        hideOnDesktop: { type: 'radio', label: 'Hide on Desktop', options: [{ label: 'Show', value: 'false' }, { label: 'Hide', value: 'true' }] },
        marginTop: { type: 'custom', label: 'Margin Top', render: ResponsiveInput }, marginBottom: { type: 'custom', label: 'Margin Bottom', render: ResponsiveInput }, marginLeft: { type: 'custom', label: 'Margin Left', render: ResponsiveInput }, marginRight: { type: 'custom', label: 'Margin Right', render: ResponsiveInput }
    },
    defaultProps: {
        layout: '100', mobileLayout: 'stack', flexRatio: 50, width: { d: '100%', t: '', m: '' }, height: { d: 'auto', t: '', m: '' }, backgroundColor: 'transparent', padding: { d: '0px', t: '', m: '' }, borderRadius: '0px', gap: { d: '0px', t: '', m: '' }, leftColumnBg: 'transparent', leftColumnPadding: '0px', leftColumnRadius: '0px', rightColumnBg: 'transparent', rightColumnPadding: '0px', rightColumnRadius: '0px', objectFit: 'contain', display: 'block', justifyContent: 'flex-start', alignment: 'left', borderWidth: '0px', borderStyle: 'none', borderColor: 'transparent', zoneBackgroundColor: 'transparent', zoneBorderWidth: '0px', zoneBorderStyle: 'none', zoneBorderColor: 'transparent', zoneBorderRadius: '0px', hideOnDesktop: 'false', marginTop: { d: '0px', t: '', m: '' }, marginBottom: { d: '0px', t: '', m: '' }, marginLeft: { d: '0px', t: '', m: '' }, marginRight: { d: '0px', t: '', m: '' }
    },
    render: (allProps: any) => {
        const { layout, flexRatio, borderRadius, objectFit, display, justifyContent, alignment, borderWidth, borderStyle, borderColor, zoneBackgroundColor, zoneBorderWidth, zoneBorderStyle, zoneBorderColor, zoneBorderRadius, hideOnDesktop, puck, id } = allProps;
        const blockId = `block-${(id || 'default').replace(/[:.]/g, '-')}`;
        const containerStyle: React.CSSProperties = {
            width: 'var(--width)', height: 'var(--height)', padding: 'var(--padding)', backgroundColor: 'var(--background-color)', borderRadius, border: `${borderWidth} ${borderStyle} ${borderColor}`,
            margin: `${allProps.marginTop ? 'var(--margin-top)' : '0'} ${alignment === 'center' ? 'auto' : (alignment === 'right' ? '0' : (allProps.marginRight ? 'var(--margin-right)' : '0'))} ${allProps.marginBottom ? 'var(--margin-bottom)' : '0'} ${alignment === 'center' ? 'auto' : (alignment === 'right' ? 'auto' : (allProps.marginLeft ? 'var(--margin-left)' : '0'))}`,
            objectFit: objectFit as any, display: display as any, gap: 'var(--gap)', justifyContent: (display === 'flex' || display === 'grid') ? justifyContent : undefined, boxSizing: 'border-box'
        }
        const zoneStyle = { padding: 'var(--zone-padding, 15px)', backgroundColor: zoneBackgroundColor, border: `${zoneBorderWidth} ${zoneBorderStyle} ${zoneBorderColor}`, borderRadius: zoneBorderRadius, minHeight: '120px', transition: 'all 0.3s ease', boxShadow: 'inset 0 0 10px rgba(0,0,0,0.02)' }
        const content = (() => {
            if (layout === '50-50') {
                const r = flexRatio || 50;
                const isMobileRow = allProps.mobileLayout === 'row';
                return (<div className="w-full"><style dangerouslySetInnerHTML={{ __html: `@media (min-width: 768px) { #${blockId}-grid { grid-template-columns: ${r}% ${100 - r}% !important; } } @media (max-width: 767px) { #${blockId} { --zone-padding: 8px; } }` }} /><div id={`${blockId}-grid`} className="grid w-full" style={{ display: 'grid', gap: 'var(--gap)', gridTemplateColumns: isMobileRow ? `${r}% ${100 - r}%` : `minmax(0, 1fr)` }}><div style={{ ...zoneStyle, backgroundColor: allProps.leftColumnBg, padding: allProps.leftColumnPadding, borderRadius: allProps.leftColumnRadius }}><puck.renderDropZone zone="left" /></div><div style={{ ...zoneStyle, backgroundColor: allProps.rightColumnBg, padding: allProps.rightColumnPadding, borderRadius: allProps.rightColumnRadius }}><puck.renderDropZone zone="right" /></div></div></div>)
            }
            if (layout === '33-33-33') {
                const isMobileRow = allProps.mobileLayout === 'row';
                return (<div className="w-full"><style dangerouslySetInnerHTML={{ __html: `@media (max-width: 767px) { #${blockId} { --zone-padding: 8px; } }` }} /><div className={cn("grid w-full", isMobileRow ? "grid-cols-3" : "grid-cols-1 md:grid-cols-3")} style={{ display: 'grid', gap: 'var(--gap)' }}><div style={zoneStyle}><puck.renderDropZone zone="col1" /></div><div style={zoneStyle}><puck.renderDropZone zone="col2" /></div><div style={zoneStyle}><puck.renderDropZone zone="col3" /></div></div></div>)
            }
            return <div className="w-full"><div style={zoneStyle}><puck.renderDropZone zone="zone" /></div></div>
        })();
        return <div id={blockId} className={cn(hideOnDesktop === 'true' ? 'hide-desktop' : '', "polychem-one-block")} style={{ ...containerStyle }}><ResponsiveStyles id={blockId} props={allProps} />{content}</div>
    }
}

export const FlexBox = {
    fields: {
        width: { type: 'custom', label: 'Width', render: ResponsiveInput }, height: { type: 'custom', label: 'Height', render: ResponsiveInput }, backgroundColor: { type: 'custom', label: 'Background Color', render: ColorPicker }, padding: { type: 'custom', label: 'Padding', render: ResponsiveInput }, borderRadius: { type: 'text', label: 'Border Radius' }, borderWidth: { type: 'text', label: 'Border Width' }, borderStyle: { type: 'select', label: 'Border Style', options: [{ label: 'None', value: 'none' }, { label: 'Solid', value: 'solid' }, { label: 'Dashed', value: 'dashed' }, { label: 'Dotted', value: 'dotted' }] }, borderColor: { type: 'custom', label: 'Border Color', render: ColorPicker }, shadow: { type: 'select', label: 'Shadow', options: [{ label: 'None', value: 'none' }, { label: 'Soft', value: '0 4px 6px -1px rgb(0 0 0 / 0.1)' }, { label: 'Medium', value: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }, { label: 'Large', value: '0 20px 25px -5px rgb(0 0 0 / 0.1)' }] }, display: { type: 'radio', label: 'Desktop Design', options: [{ label: 'Stacked (Vertical)', value: 'column' }, { label: 'One Line (Horizontal)', value: 'row' }] }, mobileDirection: { type: 'radio', label: 'Mobile Design', options: [{ label: 'Matched', value: 'match' }, { label: 'Stacked (Vertical)', value: 'column' }, { label: 'One Line (Horizontal)', value: 'row' }] }, flexWrap: { type: 'radio', label: 'Wrap images to new line?', options: [{ label: 'No (Stay in 1 Line)', value: 'nowrap' }, { label: 'Yes (Wrap)', value: 'wrap' }] }, hideOnDesktop: { type: 'radio', label: 'Show on Desktop', options: [{ label: 'ON', value: 'false' }, { label: 'OFF (Hide)', value: 'true' }] }, hideOnMobile: { type: 'radio', label: 'Show on Mobile', options: [{ label: 'ON', value: 'false' }, { label: 'OFF (Hide)', value: 'true' }] }, gap: { type: 'custom', label: 'Gap', render: ResponsiveInput }, alignment: { type: 'custom', label: 'Align Items', render: (props: any) => (<ResponsiveRadio {...props} options={[{ label: 'Start', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'End', value: 'flex-end' }]} />) }
    },
    defaultProps: {
        width: { d: 'auto', t: '', m: '' }, height: { d: 'auto', t: '', m: '' }, backgroundColor: '#ffffff', padding: { d: '20px', t: '', m: '' }, borderRadius: '12px', borderWidth: '1px', borderStyle: 'solid', borderColor: '#e2e8f0', shadow: 'none', display: 'column', mobileDirection: 'match', hideOnDesktop: 'false', hideOnMobile: 'false', flexWrap: 'nowrap', gap: { d: '12px', t: '', m: '' }, alignment: { d: 'flex-start', t: '', m: '' }
    },
    render: (allProps: any) => {
        const { width, height, backgroundColor, borderRadius, borderWidth, borderStyle, borderColor, shadow, display, mobileDirection, hideOnDesktop, hideOnMobile, flexWrap, alignment, puck, id } = allProps;
        const blockId = `box-${(id || 'default').replace(/[:.]/g, '-')}`;
        const isMobileMatch = mobileDirection === 'match';
        const finalMobileDir = isMobileMatch ? (display === 'row' ? 'row' : 'column') : mobileDirection;
        const boxStyle: React.CSSProperties = { width: 'var(--width)', height: 'var(--height)', padding: 'var(--padding)', backgroundColor, borderRadius, border: `${borderWidth} ${borderStyle} ${borderColor}`, boxShadow: shadow, display: (hideOnDesktop === 'true' && hideOnMobile === 'true') ? 'none' : 'flex', flexWrap: flexWrap as any, flexDirection: (display === 'row' ? 'row' : 'column'), alignItems: 'var(--alignment)' as any, gap: 'var(--gap)', minWidth: '100px', minHeight: '120px' };
        return (<div id={blockId} style={boxStyle} className={cn("polychem-flex-transformer", hideOnDesktop === 'true' ? 'hidden md:hidden' : '', hideOnMobile === 'true' ? 'md:flex hidden' : '')}><style dangerouslySetInnerHTML={{ __html: `@media (max-width: 767px) { #${blockId}, #${blockId} > [data-puck-dropzone], #${blockId} > .puck-dropzone, #${blockId} > div { flex-direction: ${finalMobileDir === 'row' ? 'row' : 'column'} !important; } } @media (min-width: 768px) { #${blockId}, #${blockId} > [data-puck-dropzone], #${blockId} > .puck-dropzone, #${blockId} > div { flex-direction: ${display === 'row' ? 'row' : 'column'} !important; } } #${blockId} > [data-puck-dropzone], #${blockId} > .puck-dropzone, #${blockId} > div { display: flex !important; flex-wrap: inherit !important; align-items: inherit !important; gap: inherit !important; width: 100%; padding: 0 !important; margin: 0 !important; } #${blockId} > [data-puck-dropzone] > *, #${blockId} > .puck-dropzone > *, #${blockId} > div > * { flex-shrink: 1 !important; min-width: 0 !important; }` }} /><ResponsiveStyles id={blockId} props={allProps} /><puck.renderDropZone zone="content" /></div>);
    }
}

export const Row = {
    fields: {
        layout: { type: 'select', label: 'Layout', options: [{ label: '100%', value: '100' }, { label: '50% / 50%', value: '50-50' }, { label: '33% / 33% / 33%', value: '33-33-33' }] },
        width: { type: 'custom', label: 'Width', render: ResponsiveInput }, height: { type: 'custom', label: 'Height', render: ResponsiveInput }, backgroundColor: { type: 'custom', label: 'Background', render: ResponsiveInput }, padding: { type: 'custom', label: 'Padding', render: ResponsiveInput }, borderRadius: { type: 'text', label: 'Radius' }, gap: { type: 'custom', label: 'Gap', render: ResponsiveInput }, objectFit: { type: 'select', label: 'Fit', options: [{ label: 'Contain', value: 'contain' }, { label: 'Cover', value: 'cover' }, { label: 'Fill', value: 'fill' }] },
        display: { type: 'radio', label: 'Display', options: [{ label: 'Block', value: 'block' }, { label: 'Flex', value: 'flex' }, { label: 'Grid', value: 'grid' }] }, justifyContent: { type: 'radio', label: 'Justify', options: [{ label: 'Left', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'flex-end' }] }, alignment: { type: 'radio', label: 'Align', options: [{ label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }] },
        borderWidth: { type: 'text', label: 'Border Width' }, borderStyle: { type: 'select', label: 'Border Style', options: [{ label: 'None', value: 'none' }, { label: 'Solid', value: 'solid' }, { label: 'Dashed', value: 'dashed' }, { label: 'Dotted', value: 'dotted' }] }, borderColor: { type: 'custom', label: 'Border Color', render: ColorPicker }, zoneBackgroundColor: { type: 'custom', label: 'Zone Bg', render: ColorPicker }, zoneBorderWidth: { type: 'text', label: 'Zone Border Width' }, zoneBorderStyle: { type: 'select', label: 'Zone Border Style', options: [{ label: 'None', value: 'none' }, { label: 'Solid', value: 'solid' }, { label: 'Dashed', value: 'dashed' }, { label: 'Dotted', value: 'dotted' }] }, zoneBorderColor: { type: 'custom', label: 'Zone Border Color', render: ColorPicker }, zoneBorderRadius: { type: 'text', label: 'Zone Border Radius' }, hideOnDesktop: { type: 'radio', label: 'Hide', options: [{ label: 'Show', value: 'false' }, { label: 'Hide', value: 'true' }] }, marginTop: { type: 'custom', label: 'Margin Top', render: ResponsiveInput }, marginBottom: { type: 'custom', label: 'Margin Bottom', render: ResponsiveInput }, marginLeft: { type: 'custom', label: 'Margin Left', render: ResponsiveInput }, marginRight: { type: 'custom', label: 'Margin Right', render: ResponsiveInput }
    },
    defaultProps: { layout: '100', width: { d: '100%', t: '', m: '' }, height: { d: 'auto', t: '', m: '' }, backgroundColor: { d: 'transparent', t: '', m: '' }, padding: { d: '0px', t: '', m: '' }, borderRadius: '0px', gap: { d: '10px', t: '', m: '' }, objectFit: 'contain', display: 'block', justifyContent: 'flex-start', alignment: 'left', borderWidth: '0px', borderStyle: 'none', borderColor: '#e2e8f0', zoneBackgroundColor: '#f8fafc', zoneBorderWidth: '2px', zoneBorderStyle: 'dashed', zoneBorderColor: '#cbd5e1', zoneBorderRadius: '6px', hideOnDesktop: 'false', marginTop: { d: '0px', t: '', m: '' }, marginBottom: { d: '0px', t: '', m: '' }, marginLeft: { d: '0px', t: '', m: '' }, marginRight: { d: '0px', t: '', m: '' } },
    render: (allProps: any) => {
        const { layout, borderRadius, objectFit, display, justifyContent, alignment, borderWidth, borderStyle, borderColor, zoneBackgroundColor, zoneBorderWidth, zoneBorderStyle, zoneBorderColor, zoneBorderRadius, hideOnDesktop, puck, id } = allProps;
        const blockId = `row-${(id || 'default').replace(/[:.]/g, '-')}`;
        const containerStyle: React.CSSProperties = { width: 'var(--width)', height: 'var(--height)', padding: 'var(--padding)', backgroundColor: 'var(--background-color)', borderRadius, border: `${borderWidth} ${borderStyle} ${borderColor}`, margin: `${allProps.marginTop ? 'var(--margin-top)' : '0'} ${alignment === 'center' ? 'auto' : (alignment === 'right' ? '0' : (allProps.marginRight ? 'var(--margin-right)' : '0'))} ${allProps.marginBottom ? 'var(--margin-bottom)' : '0'} ${alignment === 'center' ? 'auto' : (alignment === 'right' ? 'auto' : (allProps.marginLeft ? 'var(--margin-left)' : '0'))}`, objectFit: objectFit as any, display: display as any, gap: 'var(--gap)', justifyContent: (display === 'flex' || display === 'grid') ? justifyContent : undefined };
        const zoneStyle = { padding: '15px', backgroundColor: zoneBackgroundColor, border: `${zoneBorderWidth} ${zoneBorderStyle} ${zoneBorderColor}`, borderRadius: zoneBorderRadius, minHeight: '100px' };
        const content = (() => {
            if (layout === '50-50') return <div className="grid gap-[var(--gap)] grid-cols-1 md:grid-cols-2"><div style={zoneStyle}><puck.renderDropZone zone="left" /></div><div style={zoneStyle}><puck.renderDropZone zone="right" /></div></div>;
            if (layout === '33-33-33') return <div className="grid gap-[var(--gap)] grid-cols-1 md:grid-cols-2 lg:grid-cols-3"><div style={zoneStyle}><puck.renderDropZone zone="col1" /></div><div style={zoneStyle}><puck.renderDropZone zone="col2" /></div><div style={zoneStyle}><puck.renderDropZone zone="col3" /></div></div>;
            return <div style={{ ...containerStyle, display: 'flex', flexDirection: 'column', gap: 'var(--gap)' }}><div style={zoneStyle}><puck.renderDropZone zone="top" /></div><div style={zoneStyle}><puck.renderDropZone zone="bottom" /></div></div>;
        })();
        return <div id={blockId} className={cn(hideOnDesktop === 'true' ? 'hide-desktop' : '', "polychem-responsive-root")} style={{ ...containerStyle }}><ResponsiveStyles id={blockId} props={allProps} />{content}</div>;
    }
}

export const GridRow = {
    fields: {
        layout: { type: 'select', label: 'Layout', options: [{ label: '100%', value: '100' }, { label: 'Custom Split', value: '50-50' }, { label: '50% / 50%', value: '50-50-fixed' }, { label: '33% / 33% / 33%', value: '33-33-33' }] },
        flexRatio: { type: 'custom', label: 'Split Ratio', render: RangeInput },
        width: { type: 'custom', label: 'Width', render: ResponsiveInput }, height: { type: 'custom', label: 'Height', render: ResponsiveInput }, backgroundColor: { type: 'custom', label: 'Background', render: ResponsiveInput }, padding: { type: 'custom', label: 'Padding', render: ResponsiveInput }, borderRadius: { type: 'text', label: 'Radius' }, gap: { type: 'custom', label: 'Gap', render: ResponsiveInput }, objectFit: { type: 'select', label: 'Fit', options: [{ label: 'Contain', value: 'contain' }, { label: 'Cover', value: 'cover' }, { label: 'Fill', value: 'fill' }] },
        display: { type: 'radio', label: 'Display', options: [{ label: 'Block', value: 'block' }, { label: 'Flex', value: 'flex' }, { label: 'Grid', value: 'grid' }] }, justifyContent: { type: 'radio', label: 'Justify', options: [{ label: 'Left', value: 'flex-start' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'flex-end' }] }, alignment: { type: 'radio', label: 'Align', options: [{ label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }] },
        borderWidth: { type: 'text', label: 'Border Width' }, borderStyle: { type: 'select', label: 'Border Style', options: [{ label: 'None', value: 'none' }, { label: 'Solid', value: 'solid' }, { label: 'Dashed', value: 'dashed' }, { label: 'Dotted', value: 'dotted' }] }, borderColor: { type: 'custom', label: 'Border Color', render: ColorPicker }, zoneBackgroundColor: { type: 'custom', label: 'Zone Bg', render: ColorPicker }, zoneBorderWidth: { type: 'text', label: 'Zone Border Width' }, zoneBorderStyle: { type: 'select', label: 'Zone Border Style', options: [{ label: 'None', value: 'none' }, { label: 'Solid', value: 'solid' }, { label: 'Dashed', value: 'dashed' }, { label: 'Dotted', value: 'dotted' }] }, zoneBorderColor: { type: 'custom', label: 'Zone Border Color', render: ColorPicker }, zoneBorderRadius: { type: 'text', label: 'Zone Border Radius' }, hideOnDesktop: { type: 'radio', label: 'Hide', options: [{ label: 'Show', value: 'false' }, { label: 'Hide', value: 'true' }] }, marginTop: { type: 'custom', label: 'Margin Top', render: ResponsiveInput }, marginBottom: { type: 'custom', label: 'Margin Bottom', render: ResponsiveInput }, marginLeft: { type: 'custom', label: 'Margin Left', render: ResponsiveInput }, marginRight: { type: 'custom', label: 'Margin Right', render: ResponsiveInput }
    },
    defaultProps: { layout: '50-50', width: { d: '100%', t: '', m: '' }, height: { d: 'auto', t: '', m: '' }, backgroundColor: { d: 'transparent', t: '', m: '' }, padding: { d: '0px', t: '', m: '' }, borderRadius: '0px', gap: { d: '10px', t: '', m: '' }, objectFit: 'contain', display: 'block', justifyContent: 'flex-start', alignment: 'left', borderWidth: '0px', borderStyle: 'none', borderColor: '#e2e8f0', zoneBackgroundColor: '#f8fafc', zoneBorderWidth: '2px', zoneBorderStyle: 'dashed', zoneBorderColor: '#cbd5e1', zoneBorderRadius: '6px', hideOnDesktop: 'false', marginTop: { d: '0px', t: '', m: '' }, marginBottom: { d: '0px', t: '', m: '' }, marginLeft: { d: '0px', t: '', m: '' }, marginRight: { d: '0px', t: '', m: '' } },
    render: (allProps: any) => {
        const { layout, flexRatio, borderRadius, objectFit, display, justifyContent, alignment, borderWidth, borderStyle, borderColor, zoneBackgroundColor, zoneBorderWidth, zoneBorderStyle, zoneBorderColor, zoneBorderRadius, hideOnDesktop, puck, id } = allProps;
        const blockId = `gridrow-${(id || 'default').replace(/[:.]/g, '-')}`;
        const containerStyle: React.CSSProperties = { width: 'var(--width)', height: 'var(--height)', padding: 'var(--padding)', backgroundColor: 'var(--background-color)', borderRadius, border: `${borderWidth} ${borderStyle} ${borderColor}`, margin: `${allProps.marginTop ? 'var(--margin-top)' : '0'} ${alignment === 'center' ? 'auto' : (alignment === 'right' ? '0' : (allProps.marginRight ? 'var(--margin-right)' : '0'))} ${allProps.marginBottom ? 'var(--margin-bottom)' : '0'} ${alignment === 'center' ? 'auto' : (alignment === 'right' ? 'auto' : (allProps.marginLeft ? 'var(--margin-left)' : '0'))}`, objectFit: objectFit as any, display: display as any, gap: 'var(--gap)', justifyContent: (display === 'flex' || display === 'grid') ? justifyContent : undefined };
        const zoneStyle = { padding: '15px', backgroundColor: zoneBackgroundColor, border: `${zoneBorderWidth} ${zoneBorderStyle} ${zoneBorderColor}`, borderRadius: zoneBorderRadius, minHeight: '100px' };
        const content = (() => {
            if (layout === '50-50') {
                const r = flexRatio || 50;
                return (<div className="w-full"><style dangerouslySetInnerHTML={{ __html: `@media (min-width: 768px) { #${blockId}-grid { grid-template-columns: ${r}% ${100 - r}% !important; } }` }} /><div id={`${blockId}-grid`} className="grid w-full grid-cols-1 md:grid-cols-2" style={{ display: 'grid', gap: 'var(--gap)' }}><div style={zoneStyle}><puck.renderDropZone zone="left" /></div><div style={zoneStyle}><puck.renderDropZone zone="right" /></div></div></div>);
            }
            if (layout === '50-50-fixed') return <div className="grid gap-[var(--gap)] grid-cols-1 md:grid-cols-2"><div style={zoneStyle}><puck.renderDropZone zone="left" /></div><div style={zoneStyle}><puck.renderDropZone zone="right" /></div></div>;
            if (layout === '33-33-33') return <div className="grid gap-[var(--gap)] grid-cols-1 md:grid-cols-2 lg:grid-cols-3"><div style={zoneStyle}><puck.renderDropZone zone="col1" /></div><div style={zoneStyle}><puck.renderDropZone zone="col2" /></div><div style={zoneStyle}><puck.renderDropZone zone="col3" /></div></div>;
            return <div className="w-full"><div style={zoneStyle}><puck.renderDropZone zone="content" /></div></div>
        })();
        return <div id={blockId} className={cn(hideOnDesktop === 'true' ? 'hide-desktop' : '', "polychem-grid-root")} style={{ ...containerStyle }}><ResponsiveStyles id={blockId} props={allProps} />{content}</div>;
    }
}

export const Link = {
    fields: {
        text: { type: 'text', label: 'Link Text' }, url: { type: 'text', label: 'URL' }, color: { type: 'custom', label: 'Color', render: ColorPicker }, width: { type: 'custom', label: 'Width', render: ResponsiveInput }, alignment: { type: 'custom', label: 'Alignment', render: (props: any) => (<ResponsiveRadio {...props} options={[{ label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }]} />) }, marginTop: { type: 'custom', label: 'Margin Top', render: ResponsiveInput }, marginBottom: { type: 'custom', label: 'Margin Bottom', render: ResponsiveInput }, target: { type: 'radio', label: 'Open in', options: [{ label: 'Same Tab', value: '_self' }, { label: 'New Tab', value: '_blank' }] }, hideOnDesktop: { type: 'radio', label: 'Hide', options: [{ label: 'Show', value: 'false' }, { label: 'Hide', value: 'true' }] }
    },
    defaultProps: { text: 'Click here', url: 'https://', color: '#3b82f6', width: { d: 'auto', t: '', m: '' }, alignment: { d: 'left', t: '', m: '' }, marginTop: { d: '0px', t: '', m: '' }, marginBottom: { d: '0px', t: '', m: '' }, target: '_self', hideOnDesktop: 'false' },
    render: (allProps: any) => {
        const { text, url, color, target, hideOnDesktop, alignment, id } = allProps;
        const blockId = `link-${(id || 'default').replace(/[:.]/g, '-')}`;
        let rawUrl = typeof url === 'object' && url !== null ? (url.d || '') : (url || '');
        let finalUrl = (rawUrl && !rawUrl.startsWith('http') && !rawUrl.startsWith('/') && !rawUrl.startsWith('#')) ? `https://${rawUrl}` : rawUrl;
        const handleClick = (e: React.MouseEvent) => { if (typeof window !== 'undefined' && window.location.pathname.includes('/admin/dashboard')) { e.preventDefault(); } }
        return (<div id={blockId} style={{ textAlign: 'var(--alignment)' as any, width: '100%', marginTop: 'var(--margin-top)', marginBottom: 'var(--margin-bottom)' }} className={hideOnDesktop === 'true' ? 'hide-desktop' : ''}><ResponsiveStyles id={blockId} props={allProps} /><a href={finalUrl || '#'} target={target} rel={target === '_blank' ? 'noopener noreferrer' : undefined} onClick={handleClick} style={{ color, textDecoration: 'underline', display: 'inline-block', cursor: 'pointer', width: 'var(--width)' }}>{text}</a></div>)
    }
}

export const Button = {
    fields: {
        text: { type: 'text', label: 'Text' }, href: { type: 'text', label: 'URL' }, variant: { type: 'select', label: 'Variant', options: [{ label: 'Primary', value: 'primary' }, { label: 'Secondary', value: 'secondary' }, { label: 'Outline', value: 'outline' }, { label: 'Ghost', value: 'ghost' }] }, size: { type: 'select', label: 'Size', options: [{ label: 'Small', value: 'sm' }, { label: 'Medium', value: 'md' }, { label: 'Large', value: 'lg' }] }, width: { type: 'custom', label: 'Width', render: ResponsiveInput }, height: { type: 'custom', label: 'Height', render: ResponsiveInput }, backgroundColor: { type: 'custom', label: 'Bg Color', render: ResponsiveInput }, color: { type: 'custom', label: 'Text Color', render: ColorPicker }, padding: { type: 'custom', label: 'Padding', render: ResponsiveInput }, borderRadius: { type: 'text', label: 'Radius' }, fontSize: { type: 'custom', label: 'Font Size', render: ResponsiveInput }, fontWeight: { type: 'text', label: 'Weight' }, marginTop: { type: 'custom', label: 'Margin Top', render: ResponsiveInput }, marginBottom: { type: 'custom', label: 'Margin Bottom', render: ResponsiveInput }, alignment: { type: 'custom', label: 'Align', render: (props: any) => (<ResponsiveRadio {...props} options={[{ label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }]} />) }, hideOnDesktop: { type: 'radio', label: 'Hide', options: [{ label: 'Show', value: 'false' }, { label: 'Hide', value: 'true' }] }
    },
    defaultProps: { text: 'Click Me', href: '#', variant: 'primary', size: 'md', width: { d: 'auto', t: '', m: 'w-full' }, height: { d: 'auto', t: '', m: '' }, backgroundColor: { d: '', t: '', m: '' }, color: '', padding: { d: '12px 24px', t: '10px 20px', m: '8px 16px' }, borderRadius: '12px', fontSize: { d: '16px', t: '15px', m: '14px' }, fontWeight: '600', marginTop: { d: '0px', t: '', m: '' }, marginBottom: { d: '0px', t: '', m: '' }, alignment: { d: 'left', t: '', m: '' }, hideOnDesktop: 'false' },
    render: (allProps: any) => {
        const { text, href, borderRadius, fontWeight, alignment, hideOnDesktop, id, color, variant, size } = allProps;
        const blockId = `btn-${(id || 'default').replace(/[:.]/g, '-')}`;
        const getV = () => { switch (variant) { case 'secondary': return 'bg-slate-800 text-white'; case 'outline': return 'bg-transparent border-2 border-slate-200 text-slate-800'; case 'ghost': return 'bg-transparent text-slate-800'; default: return 'bg-blue-600 text-white'; } }
        const getS = () => { switch (size) { case 'sm': return 'text-xs px-3 py-1.5'; case 'lg': return 'text-lg px-8 py-4'; default: return 'text-sm'; } }
        return (<div id={blockId} style={{ textAlign: 'var(--alignment)' as any, width: '100%' }} className={hideOnDesktop === 'true' ? 'hide-desktop' : ''}><ResponsiveStyles id={blockId} props={allProps} /><a href={href} style={{ display: 'inline-block', width: 'var(--width)', height: 'var(--height)', backgroundColor: allProps.backgroundColor ? 'var(--background-color)' : undefined, color: color || undefined, padding: 'var(--padding)', fontSize: 'var(--font-size)', borderRadius, fontWeight: fontWeight as any, marginTop: 'var(--margin-top)', marginBottom: 'var(--margin-bottom)', textDecoration: 'none', textAlign: 'center', transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)', cursor: 'pointer', border: variant === 'outline' ? 'var(--border)' : 'none' }} className={cn("inline-flex items-center justify-center font-semibold transition-all duration-200 shadow-sm active:scale-95", getV(), getS(), allProps.width?.m === 'w-full' && 'w-full sm:w-auto')} onClick={(e) => { if (typeof window !== 'undefined' && window.location.pathname.includes('/admin/dashboard')) e.preventDefault(); }}>{text}</a></div>)
    }
}

export const List = {
    fields: {
        text: { type: 'text', label: 'Item Text' }, color: { type: 'custom', label: 'Color', render: ColorPicker }, width: { type: 'custom', label: 'Width', render: ResponsiveInput }, textAlign: { type: 'custom', label: 'Text Align', render: (props: any) => (<ResponsiveRadio {...props} options={[{ label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }]} />) }, alignment: { type: 'custom', label: 'Box Align', render: (props: any) => (<ResponsiveRadio {...props} options={[{ label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }]} />) }, fontSize: { type: 'custom', label: 'Font Size', render: ResponsiveInput }, marginTop: { type: 'custom', label: 'Margin Top', render: ResponsiveInput }, marginBottom: { type: 'custom', label: 'Margin Bottom', render: ResponsiveInput }, hideOnDesktop: { type: 'radio', label: 'Hide', options: [{ label: 'Show', value: 'false' }, { label: 'Hide', value: 'true' }] }
    },
    defaultProps: { text: 'Parent Item', color: '#334155', width: { d: 'auto', t: '', m: '' }, textAlign: { d: 'left', t: '', m: '' }, alignment: { d: 'left', t: '', m: '' }, fontSize: { d: '16px', t: '', m: '' }, marginTop: { d: '0px', t: '', m: '' }, marginBottom: { d: '8px', t: '', m: '' }, hideOnDesktop: 'false' },
    render: (allProps: any) => {
        const { text, color, hideOnDesktop, puck, alignment, id } = allProps;
        const blockId = `list-${(id || 'default').replace(/[:.]/g, '-')}`;
        const s: React.CSSProperties = { display: 'list-item', textAlign: 'var(--text-align)' as any, color, fontSize: 'var(--font-size)', width: 'var(--width)', listStyleType: 'disc', listStylePosition: 'inside', margin: normalizeResponsive(alignment).d === 'center' ? '0 auto' : (normalizeResponsive(alignment).d === 'right' ? '0 0 0 auto' : '0'), padding: 0 }
        return (<li id={blockId} style={s} className={hideOnDesktop === 'true' ? 'hide-desktop' : ''}><ResponsiveStyles id={blockId} props={allProps} /><span style={{ display: 'inline', marginBottom: '4px' }}>{text}</span><ul style={{ listStyleType: 'circle', margin: '8px 0 0 0', paddingLeft: '20px', textAlign: 'inherit', listStylePosition: 'inside' }}><puck.renderDropZone zone="children" /></ul></li>)
    }
}

export const ListItem = {
    fields: {
        text: { type: 'text', label: 'Text' }, color: { type: 'custom', label: 'Color', render: ColorPicker }, width: { type: 'custom', label: 'Width', render: ResponsiveInput }, textAlign: { type: 'custom', label: 'Text Align', render: (props: any) => (<ResponsiveRadio {...props} options={[{ label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }]} />) }, alignment: { type: 'custom', label: 'Box Align', render: (props: any) => (<ResponsiveRadio {...props} options={[{ label: 'Left', value: 'left' }, { label: 'Center', value: 'center' }, { label: 'Right', value: 'right' }]} />) }, fontSize: { type: 'custom', label: 'Font Size', render: ResponsiveInput }, marginTop: { type: 'custom', label: 'Margin Top', render: ResponsiveInput }, marginBottom: { type: 'custom', label: 'Margin Bottom', render: ResponsiveInput }, hideOnDesktop: { type: 'radio', label: 'Hide', options: [{ label: 'Show', value: 'false' }, { label: 'Hide', value: 'true' }] }
    },
    defaultProps: { text: 'List item', color: '#334155', width: { d: 'auto', t: '', m: '' }, textAlign: { d: 'left', t: '', m: '' }, alignment: { d: 'left', t: '', m: '' }, fontSize: { d: '16px', t: '', m: '' }, marginTop: { d: '0px', t: '', m: '' }, marginBottom: { d: '8px', t: '', m: '' }, hideOnDesktop: 'false' },
    render: (allProps: any) => {
        const { text, color, hideOnDesktop, alignment, id } = allProps;
        const blockId = `item-${(id || 'default').replace(/[:.]/g, '-')}`;
        const s: React.CSSProperties = { textAlign: 'var(--text-align)' as any, width: 'var(--width)', fontSize: 'var(--font-size)', marginTop: 'var(--margin-top)', marginBottom: 'var(--margin-bottom)', display: 'list-item', listStylePosition: 'inside', margin: normalizeResponsive(alignment).d === 'center' ? '0 auto' : (normalizeResponsive(alignment).d === 'right' ? '0 0 0 auto' : '0') }
        return (<li id={blockId} style={s} className={hideOnDesktop === 'true' ? 'hide-desktop' : ''}><ResponsiveStyles id={blockId} props={allProps} /><span style={{ display: 'inline', textAlign: 'left', color, margin: 0 }}>{text}</span></li>)
    }
}
